name: bloom_filter
description: A stand-alone Bloom filter implementation written in Dart.
version: 0.2.0+1
author: Kwang Yul Seo <kwangyul.seo@gmail.com>
homepage: https://github.com/kseo/bloom_filter

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  bit_vector: ^0.2.0
  crypto: ^2.0.1

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  uuid: ^0.5.3
