name: bloom_filter
description: A stand-alone Bloom filter implementation written in Dart.
version: 0.3.0
author: Kwang Yul Seo <kwangyul.seo@gmail.com>
homepage: https://github.com/kseo/bloom_filter

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  crypto: ^2.0.1
  fixnum: any
  collection: any
  bit_array: ^2.0.0

dev_dependencies:
  test: ^1.3.0
  uuid: ^2.0.0
